name: release

# Push when toc file is updated
on:
  push:
    paths:
      - 'Broker_PlayerMenu/Broker_PlayerMenu.toc'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get version
        run: echo "BROKERPLAYERMENU_VERSION=$(cat Broker_PlayerMenu/Broker_PlayerMenu.toc | grep Version | cut -d ' ' -f3)" >> $GITHUB_ENV
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "Broker_PlayerMenu-${{ env.BROKERPLAYERMENU_VERSION }}-bc.zip"
          exclusions: "*.git*"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.BROKERPLAYERMENU_VERSION }}"
          tag: "${{ env.BROKERPLAYERMENU_VERSION }}"
          artifacts: "Broker_PlayerMenu-${{ env.BROKERPLAYERMENU_VERSION }}-bc.zip"
          artifactContentType: application/zip
          generateReleaseNotes: True
          token: ${{ secrets.GITHUB_TOKEN }}
